### ISSUE TITLE
Problem with easing?

### ISSUE THREAD

**Issue by canerelci** [amcharts/animate#3]
Is there any problem with easing functions and their implementations? The default function is easeOutCubic but it runs like easeIn function. Also, it seems Animate does not support any other easing function, the new data just appears after given duration.

**Comment by Pauan** [comment]
@canerelci Yes the easing functions are correct.

[`easeOut` means that the animation starts fast and slows down as it nears the end.](http://easings.net/)

It is also possible to specify custom easing functions:

```js
chart.animateData(data, {
  duration: 5000,
  easing: function (t) {
    return t;
  }
});
```

The easing must be a function, it cannot be a string.
