### ISSUE TITLE
Piechart legend labels are bugged while animating

### ISSUE THREAD

**Issue by khaledkhalil94** [amcharts/animate#5]
Hello,

If you enable pie chart legend, you find that legend values are bugged while animation is in progress!

I've created this snippet to demonstrate the issue.
https://codepen.io/khaledkhalil94/pen/zaGpOq

**Comment by darlesson** [comment]
Hi there,

Try setting [precision](https://docs.amcharts.com/3/javascriptcharts/AmPieChart#precision) to `0`.

**Comment by khaledkhalil94** [comment]
That done it! thanks a lot.
